package com.agd.jb.state.value;

public interface ValueInterface {
	//value background interface
	static final int OPTIONBACKGROUNDHEIGHT 	= 350;
	static final int OPTIONBACKGROUNDWIDTH		= 450;
	
	static final int CLOSINGBACKGROUNDHEIGHT	= 275;
	static final int CLOSINGBACKGROUNDWIDTH		= 550;
	
	static final int PAUSEBACKGROUNDHEIGHT		= 400;
	static final int PAUSEBACKGROUNDWIDTH		= 350;

	//value option closing
	static final int CLOSINGYESBUTTONHEIGHT 	= 50;
	static final int CLOSINGYESBUTTONWIDTH		= 140;
	
	static final int CLOSINGYESPUSHHEIGHT		= CLOSINGYESBUTTONHEIGHT - 5;
	static final int CLOSINGYESPUSHWIDTH		= CLOSINGYESBUTTONWIDTH - 5;
	
	static final int CLOSINGNOBUTTONHEIGHT 		= 70;
	static final int CLOSINGNOBUTTONWIDTH		= 140;
	
	static final int CLOSINGNOPUSHHEIGHT		= CLOSINGNOBUTTONHEIGHT - 5;
	static final int CLOSINGNOPUSHWIDTH			= CLOSINGNOBUTTONWIDTH - 5;
	
	//value option Report
	static final int REPORTPLAYBUTTONHEIGHT		= 69;
	static final int REPORTPLAYBUTTONWIDTH		= 69;
	
	static final int REPORTPLAYPUSHHEIGHT		= REPORTPLAYBUTTONHEIGHT - 5;
	static final int REPORTPLAYPUSHWIDTH		= REPORTPLAYBUTTONWIDTH - 5;
	
	//value option BUTTON
	static final int GEARBUTTONHEIGHT 			= 65;
	static final int GEARBUTTONWIDTH 			= 65;
	
	static final int GEARPUSHHEIGHT				= GEARBUTTONHEIGHT - 5;
	static final int GEARPUSHWIDTH				= GEARBUTTONWIDTH - 5;
	
	static final int ONBUTTONHEIGHT				= CLOSINGYESBUTTONHEIGHT;
	static final int ONBUTTONWIDTH				= CLOSINGYESBUTTONWIDTH;
	
	static final int ONPUSHHEIGHT				= ONBUTTONHEIGHT - 5;
	static final int ONPUSHWIDTH				= ONBUTTONWIDTH - 5;
	
	static final int OFFBUTTONHEIGHT			= CLOSINGYESBUTTONHEIGHT ;
	static final int OFFBUTTONWIDTH				= CLOSINGYESBUTTONWIDTH;
	
	static final int OFFPUSHHEIGHT				= OFFBUTTONHEIGHT - 5;
	static final int OFFPUSHWIDTH				= OFFBUTTONWIDTH - 5;
	
	static final int OPTIONCREDITBUTTONHEIGHT	= CLOSINGYESBUTTONHEIGHT;
	static final int OPTIONCREDITBUTTONWIDTH	= CLOSINGYESBUTTONWIDTH;
	
	static final int OPTIONCREDITPUSHHEIGHT		=  OPTIONCREDITBUTTONHEIGHT - 5;
	static final int OPTIONCREDITPUSHWIDTH		=  OPTIONCREDITBUTTONWIDTH - 5;
	
	//value pause interface button
	
	static final int PAUSEPOCKETBUTTONHEIGHT	= CLOSINGYESBUTTONHEIGHT;
	static final int PAUSEPOCKETBUTTONWIDTH 	= CLOSINGYESBUTTONWIDTH;
	
	static final int PAUSEPOCKETPUSHHEIGHT		= PAUSEPOCKETBUTTONHEIGHT - 5;
	static final int PAUSEPOCKETPUSHWIDTH 		= PAUSEPOCKETBUTTONWIDTH - 5;
	
	static final int PAUSEOPTIONBUTTONHEIGHT	= CLOSINGYESBUTTONHEIGHT + 10;
	static final int PAUSEOPTIONBUTTONWIDTH 	= CLOSINGYESBUTTONWIDTH;

	static final int PAUSEOPTIONPUSHNHEIGHT		= PAUSEOPTIONBUTTONHEIGHT - 5;
	static final int PAUSEOPTIONPUSHWIDTH 		= PAUSEOPTIONBUTTONWIDTH - 5;
	
	static final int PAUSEEXITBUTTONHEIGHT		= CLOSINGYESBUTTONHEIGHT+ 10;
	static final int PAUSEEXITBUTTONWIDTH  		= CLOSINGYESBUTTONWIDTH;
	
	static final int PAUSEEXITPUSHHEIGHT		= PAUSEEXITBUTTONHEIGHT - 5;
	static final int PAUSEEXITPUSHWIDTH 		= PAUSEEXITBUTTONWIDTH - 5;
}
